In [232]:
import pandas as pd
import numpy as np
from api import MedalTableOperation

database = MedalTableOperation().search()
database

        id  gold  silver  bronze  edition_id country_noc  total
0        1    11       7       2           1         USA     20
1        2    10      18      19           1         GRE     47
2        3     6       5       2           1         GER     13
3        4     5       4       2           1         FRA     11
4        5     2       3       2           1         GBR      7
...    ...   ...     ...     ...         ...         ...    ...
1682  1803     1       1       0           4         CAN      2
1683  1804     1       1       0           4         NOR      2
1684  1805     0       1       2           4         NED      3
1685  1806     0       0       3           4         AUS      3
1686  1807     0       0       2           4         BOH      2

[1687 rows x 7 columns]

In [233]:
df = pd.read_csv(
    "D:\Code\data_engineering_project\data\processed\olympic_medal_tally.csv")
df

<>:2: SyntaxWarning:

invalid escape sequence '\C'

<>:2: SyntaxWarning:

invalid escape sequence '\C'

C:\Users\Admin\AppData\Local\Temp\ipykernel_28656\2862838224.py:2: SyntaxWarning:

invalid escape sequence '\C'

      edition_id country_noc  gold  silver  bronze
0              1         USA    11       7       2
1              1         GRE    10      18      19
2              1         GER     6       5       2
3              1         FRA     5       4       2
4              1         GBR     2       3       2
...          ...         ...   ...     ...     ...
1802           4         CAN     1       1       0
1803           4         NOR     1       1       0
1804           4         NED     0       1       2
1805           4         AUS     0       0       3
1806           4         BOH     0       0       2

[1807 rows x 5 columns]

In [234]:

from country import CountryOperation, GameOperation


nocTable = pd.DataFrame(CountryOperation.search().json())

medalTable = MedalTableOperation.search()

olympicEditionTable = pd.DataFrame(GameOperation.search().json())
olympicEditionTable = olympicEditionTable[['edition_id', 'edition']]

medalTable

        id  gold  silver  bronze  edition_id country_noc  total
0        1    11       7       2           1         USA     20
1        2    10      18      19           1         GRE     47
2        3     6       5       2           1         GER     13
3        4     5       4       2           1         FRA     11
4        5     2       3       2           1         GBR      7
...    ...   ...     ...     ...         ...         ...    ...
1682  1803     1       1       0           4         CAN      2
1683  1804     1       1       0           4         NOR      2
1684  1805     0       1       2           4         NED      3
1685  1806     0       0       3           4         AUS      3
1686  1807     0       0       2           4         BOH      2

[1687 rows x 7 columns]

In [235]:
medalTable, nocTable, olympicEditionTable

(        id  gold  silver  bronze  edition_id country_noc  total
 0        1    11       7       2           1         USA     20
 1        2    10      18      19           1         GRE     47
 2        3     6       5       2           1         GER     13
 3        4     5       4       2           1         FRA     11
 4        5     2       3       2           1         GBR      7
 ...    ...   ...     ...     ...         ...         ...    ...
 1682  1803     1       1       0           4         CAN      2
 1683  1804     1       1       0           4         NOR      2
 1684  1805     0       1       2           4         NED      3
 1685  1806     0       0       3           4         AUS      3
 1686  1807     0       0       2           4         BOH      2

 [1687 rows x 7 columns],
      noc                 country
 0    AFG             Afghanistan
 1    ALB                 Albania
 2    ALG                 Algeria
 3    ASA          American Samoa
 4    AND                 Andorra
 ..   ...                     ...
 230  WIF  West Indies Federation
 231  YEM                   Yemen
 232  YUG              Yugoslavia
 233  ZAM                  Zambia
 234  ZIM                Zimbabwe

 [235 rows x 2 columns],
     edition_id               edition
 0            1  1896 Summer Olympics
 1            4     1906 Intercalated
 2            5  1908 Summer Olympics
 3            6  1912 Summer Olympics
 4            7  1920 Summer Olympics
 5            8  1924 Summer Olympics
 6            9  1928 Summer Olympics
 7           10  1932 Summer Olympics
 8           11  1936 Summer Olympics
 9           12  1948 Summer Olympics
 10          13  1952 Summer Olympics
 11          14  1956 Summer Olympics
 12          15  1960 Summer Olympics
 13          16  1964 Summer Olympics
 14          17  1968 Summer Olympics
 15          18  1972 Summer Olympics
 16          19  1976 Summer Olympics
 17          20  1980 Summer Olympics
 18          21  1984 Summer Olympics
 19          22  1988 Summer Olympics
 20          23  1992 Summer Olympics
 21          24  1996 Summer Olympics
 22          25  2000 Summer Olympics
 23          26  2004 Summer Olympics
 24          29  1924 Winter Olympics
 25          30  1928 Winter Olympics
 26          31  1932 Winter Olympics
 27          32  1936 Winter Olympics
 28          33  1948 Winter Olympics
 29          34  1952 Winter Olympics
 30          35  1956 Winter Olympics
 31          36  1960 Winter Olympics
 32          37  1964 Winter Olympics
 33          38  1968 Winter Olympics
 34          39  1972 Winter Olympics
 35          40  1976 Winter Olympics
 36          41  1980 Winter Olympics
 37          42  1984 Winter Olympics
 38          43  1988 Winter Olympics
 39          44  1992 Winter Olympics
 40          45  1994 Winter Olympics
 41          46  1998 Winter Olympics
 42          47  2002 Winter Olympics
 43          48       1956 Equestrian
 44          49  2006 Winter Olympics
 45          53  2008 Summer Olympics
 46          54  2012 Summer Olympics
 47          57  2010 Winter Olympics
 48          58  2014 Winter Olympics
 49          59  2016 Summer Olympics
 50          60  2018 Winter Olympics
 51          62  2022 Winter Olympics
 52          72  2026 Winter Olympics)

In [236]:
medalTable = pd.merge(left=medalTable, right=nocTable,
                        left_on='country_noc', right_on='noc', how='left')
medalTable = pd.merge(left=medalTable, right=olympicEditionTable,
                      left_on='edition_id', right_on='edition_id', how='left')
medalTable.drop(columns=['country_noc'], inplace=True)

medalTable

        id  gold  silver  ...  noc        country               edition
0        1    11       7  ...  USA  United States  1896 Summer Olympics
1        2    10      18  ...  GRE         Greece  1896 Summer Olympics
2        3     6       5  ...  GER        Germany  1896 Summer Olympics
3        4     5       4  ...  FRA         France  1896 Summer Olympics
4        5     2       3  ...  GBR  Great Britain  1896 Summer Olympics
...    ...   ...     ...  ...  ...            ...                   ...
1682  1803     1       1  ...  CAN         Canada     1906 Intercalated
1683  1804     1       1  ...  NOR         Norway     1906 Intercalated
1684  1805     0       1  ...  NED    Netherlands     1906 Intercalated
1685  1806     0       0  ...  AUS      Australia     1906 Intercalated
1686  1807     0       0  ...  BOH        Bohemia     1906 Intercalated

[1687 rows x 9 columns]

In [237]:
nocTable

     noc                 country
0    AFG             Afghanistan
1    ALB                 Albania
2    ALG                 Algeria
3    ASA          American Samoa
4    AND                 Andorra
..   ...                     ...
230  WIF  West Indies Federation
231  YEM                   Yemen
232  YUG              Yugoslavia
233  ZAM                  Zambia
234  ZIM                Zimbabwe

[235 rows x 2 columns]

In [238]:
nocTable = pd.merge(left=nocTable, right=medalTable[['noc']],
                    left_on='noc', right_on='noc', how='right')
nocTable.drop_duplicates(subset='noc', inplace=True)
nocTable

      noc                    country
0     USA              United States
1     GRE                     Greece
2     GER                    Germany
3     FRA                     France
4     GBR              Great Britain
...   ...                        ...
1190  FIJ                       Fiji
1191  JOR                     Jordan
1192  KOS                     Kosovo
1379  LIE              Liechtenstein
1615  ROC  Russian Olympic Committee

[151 rows x 2 columns]

In [239]:
medalTable['year'] = medalTable['edition'].str[:4]
medalTable['year'] = pd.Categorical(medalTable['year'], ordered=True)
medalTable

        id  gold  silver  ...        country               edition  year
0        1    11       7  ...  United States  1896 Summer Olympics  1896
1        2    10      18  ...         Greece  1896 Summer Olympics  1896
2        3     6       5  ...        Germany  1896 Summer Olympics  1896
3        4     5       4  ...         France  1896 Summer Olympics  1896
4        5     2       3  ...  Great Britain  1896 Summer Olympics  1896
...    ...   ...     ...  ...            ...                   ...   ...
1682  1803     1       1  ...         Canada     1906 Intercalated  1906
1683  1804     1       1  ...         Norway     1906 Intercalated  1906
1684  1805     0       1  ...    Netherlands     1906 Intercalated  1906
1685  1806     0       0  ...      Australia     1906 Intercalated  1906
1686  1807     0       0  ...        Bohemia     1906 Intercalated  1906

[1687 rows x 10 columns]

In [240]:
medalTable[medalTable['noc'] == "CAN"].sort_values(by='year')

        id  gold  silver  bronze  ...  noc  country               edition  year
1682  1803     1       1       0  ...  CAN   Canada     1906 Intercalated  1906
17      45     3       3      10  ...  CAN   Canada  1908 Summer Olympics  1908
39      67     3       2       3  ...  CAN   Canada  1912 Summer Olympics  1912
60      88     3       3       3  ...  CAN   Canada  1920 Summer Olympics  1920
1230  1351     1       0       0  ...  CAN   Canada  1924 Winter Olympics  1924
93     121     0       3       1  ...  CAN   Canada  1924 Summer Olympics  1924
1238  1359     1       0       0  ...  CAN   Canada  1928 Winter Olympics  1928
112    140     4       4       7  ...  CAN   Canada  1928 Summer Olympics  1928
1249  1370     1       1       5  ...  CAN   Canada  1932 Winter Olympics  1932
148    176     2       5       9  ...  CAN   Canada  1932 Summer Olympics  1932
1264  1385     0       1       0  ...  CAN   Canada  1936 Winter Olympics  1936
180    208     1       3       5  ...  CAN   Canada  1936 Summer Olympics  1936
1272  1393     2       0       1  ...  CAN   Canada  1948 Winter Olympics  1948
220    248     0       2       2  ...  CAN   Canada  1948 Summer Olympics  1948
254    282     1       2       0  ...  CAN   Canada  1952 Summer Olympics  1952
1285  1406     1       0       1  ...  CAN   Canada  1952 Winter Olympics  1952
1302  1423     0       1       2  ...  CAN   Canada  1956 Winter Olympics  1956
291    319     2       1       2  ...  CAN   Canada  1956 Summer Olympics  1956
1667  1788     0       0       1  ...  CAN   Canada       1956 Equestrian  1956
345    373     0       1       0  ...  CAN   Canada  1960 Summer Olympics  1960
1312  1433     2       1       1  ...  CAN   Canada  1960 Winter Olympics  1960
379    407     1       2       1  ...  CAN   Canada  1964 Summer Olympics  1964
1328  1449     1       1       1  ...  CAN   Canada  1964 Winter Olympics  1964
421    449     1       3       1  ...  CAN   Canada  1968 Summer Olympics  1968
1346  1467     1       1       1  ...  CAN   Canada  1968 Winter Olympics  1968
469    497     0       2       3  ...  CAN   Canada  1972 Summer Olympics  1972
1365  1486     0       1       0  ...  CAN   Canada  1972 Winter Olympics  1972
517    545     0       5       6  ...  CAN   Canada  1976 Summer Olympics  1976
1376  1497     1       1       1  ...  CAN   Canada  1976 Winter Olympics  1976
1395  1516     0       1       1  ...  CAN   Canada  1980 Winter Olympics  1980
1408  1529     2       1       1  ...  CAN   Canada  1984 Winter Olympics  1984
573    601    10      18      16  ...  CAN   Canada  1984 Summer Olympics  1984
1430  1551     0       2       3  ...  CAN   Canada  1988 Winter Olympics  1988
633    661     3       2       5  ...  CAN   Canada  1988 Summer Olympics  1988
1443  1564     2       3       2  ...  CAN   Canada  1992 Winter Olympics  1992
677    705     7       4       7  ...  CAN   Canada  1992 Summer Olympics  1992
1461  1582     3       6       4  ...  CAN   Canada  1994 Winter Olympics  1994
751    779     3      11       8  ...  CAN   Canada  1996 Summer Olympics  1996
1480  1601     6       5       4  ...  CAN   Canada  1998 Winter Olympics  1998
833    861     3       3       8  ...  CAN   Canada  2000 Summer Olympics  2000
1504  1625     7       3       7  ...  CAN   Canada  2002 Winter Olympics  2002
910    938     3       6       3  ...  CAN   Canada  2004 Summer Olympics  2004
1529  1650     7      10       7  ...  CAN   Canada  2006 Winter Olympics  2006
983   1011     3       9       8  ...  CAN   Canada  2008 Summer Olympics  2008
1551  1672    14       7       5  ...  CAN   Canada  2010 Winter Olympics  2010
1077  1105     2       6      10  ...  CAN   Canada  2012 Summer Olympics  2012
1579  1700    10      10       5  ...  CAN   Canada  2014 Winter Olympics  2014
1156  1184     4       3      15  ...  CAN   Canada  2016 Summer Olympics  2016
1605  1726    11       8      10  ...  CAN   Canada  2018 Winter Olympics  2018
1643  1764     4       8      14  ...  CAN   Canada  2022 Winter Olympics  2022

[50 rows x 10 columns]

In [241]:
medalTable.groupby(['year','noc'])['total'].sum().reset_index()

C:\Users\Admin\AppData\Local\Temp\ipykernel_28656\2316782094.py:1: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

      year  noc  total
0     1896  AFG      0
1     1896  AHO      0
2     1896  ALG      0
3     1896  ANZ      0
4     1896  ARG      0
...    ...  ...    ...
5280  2022  VIE      0
5281  2022  WIF      0
5282  2022  YUG      0
5283  2022  ZAM      0
5284  2022  ZIM      0

[5285 rows x 3 columns]

In [242]:
medalTable[~(medalTable['edition'].str.contains('winter',case=False)|medalTable['edition'].str.contains('summer',case=False))]

        id  gold  silver  bronze  ...  noc        country            edition  year
1662  1783     3       0       0  ...  SWE         Sweden    1956 Equestrian  1956
1663  1784     2       3       1  ...  GER        Germany    1956 Equestrian  1956
1664  1785     1       0       2  ...  GBR  Great Britain    1956 Equestrian  1956
1665  1786     0       2       1  ...  ITA          Italy    1956 Equestrian  1956
1666  1787     0       1       0  ...  DEN        Denmark    1956 Equestrian  1956
1667  1788     0       0       1  ...  CAN         Canada    1956 Equestrian  1956
1668  1789     0       0       1  ...  SUI    Switzerland    1956 Equestrian  1956
1669  1790    15       9      16  ...  FRA         France  1906 Intercalated  1906
1670  1791    12       6       6  ...  USA  United States  1906 Intercalated  1906
1671  1792     8      14      13  ...  GRE         Greece  1906 Intercalated  1906
1672  1793     8      11       5  ...  GBR  Great Britain  1906 Intercalated  1906
1673  1794     7       6       3  ...  ITA          Italy  1906 Intercalated  1906
1674  1795     4       6       5  ...  GER        Germany  1906 Intercalated  1906
1675  1796     4       3       1  ...  SUI    Switzerland  1906 Intercalated  1906
1676  1797     3       3       3  ...  AUT        Austria  1906 Intercalated  1906
1677  1798     3       2       1  ...  DEN        Denmark  1906 Intercalated  1906
1678  1799     2       5       7  ...  SWE         Sweden  1906 Intercalated  1906
1679  1800     2       5       3  ...  HUN        Hungary  1906 Intercalated  1906
1680  1801     2       2       3  ...  BEL        Belgium  1906 Intercalated  1906
1681  1802     2       1       1  ...  FIN        Finland  1906 Intercalated  1906
1682  1803     1       1       0  ...  CAN         Canada  1906 Intercalated  1906
1683  1804     1       1       0  ...  NOR         Norway  1906 Intercalated  1906
1684  1805     0       1       2  ...  NED    Netherlands  1906 Intercalated  1906
1685  1806     0       0       3  ...  AUS      Australia  1906 Intercalated  1906
1686  1807     0       0       2  ...  BOH        Bohemia  1906 Intercalated  1906

[25 rows x 10 columns]

In [243]:
import plotly.express as px


medalTableByYear = medalTable.groupby(['year', 'noc'])[['gold','silver','bronze','total']].sum().reset_index()

medalTableByYear[medalTableByYear['noc'] == 'CAN']

C:\Users\Admin\AppData\Local\Temp\ipykernel_28656\1267136327.py:4: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

      year  noc  gold  silver  bronze  total
20    1896  CAN     0       0       0      0
171   1906  CAN     1       1       0      2
322   1908  CAN     3       3      10     16
473   1912  CAN     3       2       3      8
624   1920  CAN     3       3       3      9
775   1924  CAN     1       3       1      5
926   1928  CAN     5       4       7     16
1077  1932  CAN     3       6      14     23
1228  1936  CAN     1       4       5     10
1379  1948  CAN     2       2       3      7
1530  1952  CAN     2       2       1      5
1681  1956  CAN     2       2       5      9
1832  1960  CAN     2       2       1      5
1983  1964  CAN     2       3       2      7
2134  1968  CAN     2       4       2      8
2285  1972  CAN     0       3       3      6
2436  1976  CAN     1       6       7     14
2587  1980  CAN     0       1       1      2
2738  1984  CAN    12      19      17     48
2889  1988  CAN     3       4       8     15
3040  1992  CAN     9       7       9     25
3191  1994  CAN     3       6       4     13
3342  1996  CAN     3      11       8     22
3493  1998  CAN     6       5       4     15
3644  2000  CAN     3       3       8     14
3795  2002  CAN     7       3       7     17
3946  2004  CAN     3       6       3     12
4097  2006  CAN     7      10       7     24
4248  2008  CAN     3       9       8     20
4399  2010  CAN    14       7       5     26
4550  2012  CAN     2       6      10     18
4701  2014  CAN    10      10       5     25
4852  2016  CAN     4       3      15     22
5003  2018  CAN    11       8      10     29
5154  2022  CAN     4       8      14     26

      year  noc  gold  silver  bronze  total                 country
0     1896  AFG     0       0       0      0             Afghanistan
1     1896  AHO     0       0       0      0    Netherlands Antilles
2     1896  ALG     0       0       0      0                 Algeria
3     1896  ANZ     0       0       0      0             Australasia
4     1896  ARG     0       0       0      0               Argentina
...    ...  ...   ...     ...     ...    ...                     ...
5280  2022  VIE     0       0       0      0                 Vietnam
5281  2022  WIF     0       0       0      0  West Indies Federation
5282  2022  YUG     0       0       0      0              Yugoslavia
5283  2022  ZAM     0       0       0      0                  Zambia
5284  2022  ZIM     0       0       0      0                Zimbabwe

[5285 rows x 7 columns]

In [246]:
topFiveHighestTotal = medalTableByYear.groupby(['noc'])['total'].sum(
).reset_index().sort_values(by='total', ascending=False).head(5)

# Create the line plot
fig = px.line(medalTableByYear[medalTableByYear['noc'].isin(topFiveHighestTotal['noc'].tolist())], x='year', y='total', color='noc',
              title='Country Consistency Over Time (Total Medals)',
              labels={'total': 'Total Medals', 'noc': 'Country'})
fig

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'Country=FRA<br>year=%{x}<br>Total Medals=%{y}<extra></extra>',
              'legendgroup': 'FRA',
              'line': {'color': '#636efa', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'FRA',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': array(['1896', '1906', '1908', '1912', '1920', '1924', '1928', '1932', '1936',
                          '1948', '1952', '1956', '1960', '1964', '1968', '1972', '1976', '1980',
                          '1984', '1988', '1992', '1994', '1996', '1998', '2000', '2002', '2004',
                          '2006', '2008', '2010', '2012', '2014', '2016', '2018', '2022'],
                         dtype=object),
              'xaxis': 'x',
              'y': array([11, 40, 19, 15, 42, 44, 26, 21, 20, 37, 19, 14,  8, 22, 24, 16, 10, 15,
                          31, 18, 38,  5, 37,  8, 38, 11, 33,  9, 43, 11, 35, 15, 42, 15, 14]),
              'yaxis': 'y'},
             {'hovertemplate': 'Country=GBR<br>year=%{x}<br>Total Medals=%{y}<extra></extra>',
              'legendgroup': 'GBR',
              'line': {'color': '#EF553B', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'GBR',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': array(['1896', '1906', '1908', '1912', '1920', '1924', '1928', '1932', '1936',
                          '1948', '1952', '1956', '1960', '1964', '1968', '1972', '1976', '1980',
                          '1984', '1988', '1992', '1994', '1996', '1998', '2000', '2002', '2004',
                          '2006', '2008', '2010', '2012', '2014', '2016', '2018', '2022'],
                         dtype=object),
              'xaxis': 'x',
              'y': array([  7,  24, 146,  41,  43,  39,  23,  17,  17,  29,  12,  24,  20,  19,
                           13,  18,  14,  22,  38,  24,  20,   2,  15,   1,  28,   2,  30,   1,
                           51,   1,  65,   5,  67,   5,   2]),
              'yaxis': 'y'},
             {'hovertemplate': 'Country=GER<br>year=%{x}<br>Total Medals=%{y}<extra></extra>',
              'legendgroup': 'GER',
              'line': {'color': '#00cc96', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'GER',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': array(['1896', '1906', '1908', '1912', '1920', '1924', '1928', '1932', '1936',
                          '1948', '1952', '1956', '1960', '1964', '1968', '1972', '1976', '1980',
                          '1984', '1988', '1992', '1994', '1996', '1998', '2000', '2002', '2004',
                          '2006', '2008', '2010', '2012', '2014', '2016', '2018', '2022'],
                         dtype=object),
              'xaxis': 'x',
              'y': array([ 13,  15,  13,  26,   0,   0,  40,  26, 107,   0,  31,  28,  50,  59,
                            0,   0,   0,   0,   0,   0, 108,  24,  65,  29,  56,  36,  49,  29,
                           41,  30,  44,  19,  42,  31,  27]),
              'yaxis': 'y'},
             {'hovertemplate': 'Country=URS<br>year=%{x}<br>Total Medals=%{y}<extra></extra>',
              'legendgroup': 'URS',
              'line': {'color': '#ab63fa', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'URS',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': array(['1896', '1906', '1908', '1912', '1920', '1924', '1928', '1932', '1936',
                          '1948', '1952', '1956', '1960', '1964', '1968', '1972', '1976', '1980',
                          '1984', '1988', '1992', '1994', '1996', '1998', '2000', '2002', '2004',
                          '2006', '2008', '2010', '2012', '2014', '2016', '2018', '2022'],
                         dtype=object),
              'xaxis': 'x',
              'y': array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  71, 114, 124, 121,
                          104, 115, 152, 217,  25, 161,   0,   0,   0,   0,   0,   0,   0,   0,
                            0,   0,   0,   0,   0,   0,   0]),
              'yaxis': 'y'},
             {'hovertemplate': 'Country=USA<br>year=%{x}<br>Total Medals=%{y}<extra></extra>',
              'legendgroup': 'USA',
              'line': {'color': '#FFA15A', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'USA',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': array(['1896', '1906', '1908', '1912', '1920', '1924', '1928', '1932', '1936',
                          '1948', '1952', '1956', '1960', '1964', '1968', '1972', '1976', '1980',
                          '1984', '1988', '1992', '1994', '1996', '1998', '2000', '2002', '2004',
                          '2006', '2008', '2010', '2012', '2014', '2016', '2018', '2022'],
                         dtype=object),
              'xaxis': 'x',
              'y': array([ 20,  24,  47,  64,  95, 103,  62, 122,  61,  93,  87,  81,  81,  97,
                          114, 102, 104,  12, 182, 100, 119,  13, 101,  13,  93,  34, 101,  25,
                          112,  37, 104,  28, 121,  23,  25]),
              'yaxis': 'y'}],
    'layout': {'legend': {'title': {'text': 'Country'}, 'tracegroupgap': 0},
               'template': '...',
               'title': {'text': 'Country Consistency Over Time (Total Medals)'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'year'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'Total Medals'}}}
})