In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("../data/processed/Olympic_Games_Summary.csv")
df.head()

,edition,edition_id,edition_url,year,city,country_flag_url,country_noc,start_date,end_date,isHeld,competition_start_date,competition_end_date
0,1896 Summer Olympics,1,/editions/1,1896,Athina,https://olympedia-flags.s3.eu-central-1.amazon...,GRE,1896-4-6,1896-4-15,True,1896-4-6,1896-4-13
1,1900 Summer Olympics,2,/editions/2,1900,Paris,https://olympedia-flags.s3.eu-central-1.amazon...,FRA,NaN,NaN,True,1900-5-14,1900-10-28
2,1904 Summer Olympics,3,/editions/3,1904,St. Louis,https://olympedia-flags.s3.eu-central-1.amazon...,USA,1904-5-14,NaN,True,1904-7-1,1904-11-26
3,1908 Summer Olympics,5,/editions/5,1908,London,https://olympedia-flags.s3.eu-central-1.amazon...,GBR,1908-7-13,1908-7-25,True,1908-4-27,1908-10-31
4,1912 Summer Olympics,6,/editions/6,1912,Stockholm,https://olympedia-flags.s3.eu-central-1.amazon...,SWE,1912-7-6,1912-7-15,True,1912-5-5,1912-7-27

In [5]:
df['start_date'] = pd.to_datetime(df['start_date']).dt.strftime('%Y-%m-%d')
df.head()

,edition,edition_id,edition_url,year,city,country_flag_url,country_noc,start_date,end_date,isHeld,competition_start_date,competition_end_date
0,1896 Summer Olympics,1,/editions/1,1896,Athina,https://olympedia-flags.s3.eu-central-1.amazon...,GRE,1896-04-06,1896-4-15,True,1896-4-6,1896-4-13
1,1900 Summer Olympics,2,/editions/2,1900,Paris,https://olympedia-flags.s3.eu-central-1.amazon...,FRA,NaN,NaN,True,1900-5-14,1900-10-28
2,1904 Summer Olympics,3,/editions/3,1904,St. Louis,https://olympedia-flags.s3.eu-central-1.amazon...,USA,1904-05-14,NaN,True,1904-7-1,1904-11-26
3,1908 Summer Olympics,5,/editions/5,1908,London,https://olympedia-flags.s3.eu-central-1.amazon...,GBR,1908-07-13,1908-7-25,True,1908-4-27,1908-10-31
4,1912 Summer Olympics,6,/editions/6,1912,Stockholm,https://olympedia-flags.s3.eu-central-1.amazon...,SWE,1912-07-06,1912-7-15,True,1912-5-5,1912-7-27

In [6]:
df['end_date'] = pd.to_datetime(df['end_date']).dt.strftime('%Y-%m-%d')
df.head()

,edition,edition_id,edition_url,year,city,country_flag_url,country_noc,start_date,end_date,isHeld,competition_start_date,competition_end_date
0,1896 Summer Olympics,1,/editions/1,1896,Athina,https://olympedia-flags.s3.eu-central-1.amazon...,GRE,1896-04-06,1896-04-15,True,1896-4-6,1896-4-13
1,1900 Summer Olympics,2,/editions/2,1900,Paris,https://olympedia-flags.s3.eu-central-1.amazon...,FRA,NaN,NaN,True,1900-5-14,1900-10-28
2,1904 Summer Olympics,3,/editions/3,1904,St. Louis,https://olympedia-flags.s3.eu-central-1.amazon...,USA,1904-05-14,NaN,True,1904-7-1,1904-11-26
3,1908 Summer Olympics,5,/editions/5,1908,London,https://olympedia-flags.s3.eu-central-1.amazon...,GBR,1908-07-13,1908-07-25,True,1908-4-27,1908-10-31
4,1912 Summer Olympics,6,/editions/6,1912,Stockholm,https://olympedia-flags.s3.eu-central-1.amazon...,SWE,1912-07-06,1912-07-15,True,1912-5-5,1912-7-27

In [7]:
df['competition_start_date'] = pd.to_datetime(df['competition_start_date']).dt.strftime('%Y-%m-%d')
df.head()

,edition,edition_id,edition_url,year,city,country_flag_url,country_noc,start_date,end_date,isHeld,competition_start_date,competition_end_date
0,1896 Summer Olympics,1,/editions/1,1896,Athina,https://olympedia-flags.s3.eu-central-1.amazon...,GRE,1896-04-06,1896-04-15,True,1896-04-06,1896-4-13
1,1900 Summer Olympics,2,/editions/2,1900,Paris,https://olympedia-flags.s3.eu-central-1.amazon...,FRA,NaN,NaN,True,1900-05-14,1900-10-28
2,1904 Summer Olympics,3,/editions/3,1904,St. Louis,https://olympedia-flags.s3.eu-central-1.amazon...,USA,1904-05-14,NaN,True,1904-07-01,1904-11-26
3,1908 Summer Olympics,5,/editions/5,1908,London,https://olympedia-flags.s3.eu-central-1.amazon...,GBR,1908-07-13,1908-07-25,True,1908-04-27,1908-10-31
4,1912 Summer Olympics,6,/editions/6,1912,Stockholm,https://olympedia-flags.s3.eu-central-1.amazon...,SWE,1912-07-06,1912-07-15,True,1912-05-05,1912-7-27

In [8]:
df['competition_end_date'] = pd.to_datetime(df['competition_end_date']).dt.strftime('%Y-%m-%d')
df.head()

,edition,edition_id,edition_url,year,city,country_flag_url,country_noc,start_date,end_date,isHeld,competition_start_date,competition_end_date
0,1896 Summer Olympics,1,/editions/1,1896,Athina,https://olympedia-flags.s3.eu-central-1.amazon...,GRE,1896-04-06,1896-04-15,True,1896-04-06,1896-04-13
1,1900 Summer Olympics,2,/editions/2,1900,Paris,https://olympedia-flags.s3.eu-central-1.amazon...,FRA,NaN,NaN,True,1900-05-14,1900-10-28
2,1904 Summer Olympics,3,/editions/3,1904,St. Louis,https://olympedia-flags.s3.eu-central-1.amazon...,USA,1904-05-14,NaN,True,1904-07-01,1904-11-26
3,1908 Summer Olympics,5,/editions/5,1908,London,https://olympedia-flags.s3.eu-central-1.amazon...,GBR,1908-07-13,1908-07-25,True,1908-04-27,1908-10-31
4,1912 Summer Olympics,6,/editions/6,1912,Stockholm,https://olympedia-flags.s3.eu-central-1.amazon...,SWE,1912-07-06,1912-07-15,True,1912-05-05,1912-07-27

In [9]:
df.to_csv('../data/processed/Olympic_Games_Summary.csv', index=False)